### ISSUE TITLE
Add Tests 

### ISSUE THREAD

**Issue by mgill25** [kanishkdudeja/nginx-logs-replay#10]
Thinking that we should have tests here. Basic functional tests, perhaps set it up on Travis? :)

**Comment by kanishkdudeja** [comment]
Can't agree more mate :)

**Comment by kanishkdudeja** [comment]
@mgill25 In order to write unit tests in the Idiomatic Go way, I read the following articles for my last project (https://github.com/kanishkdudeja/bloglory/) and I felt that they all discuss a common methodology for writing Go code which also makes testing using mocks easy:

https://medium.com/@benbjohnson/structuring-applications-in-go-3b04be4ff091
https://peter.bourgon.org/blog/2017/06/09/theory-of-modern-go.html
https://www.oreilly.com/ideas/how-to-ship-production-grade-go
https://medium.com/@benbjohnson/standard-package-layout-7cdbc8391fc1

I feel that if we can both agree on these, then it would make the source code more consistent from a structuring and designing perspective.

**Comment by mgill25** [comment]
Awesome stuff. I'll go through these links tonight!
