### ISSUE TITLE
Better logging and error dumping

### ISSUE THREAD

**Issue by mgill25** [kanishkdudeja/nginx-logs-replay#12]
I really dislike that we have to open/check/write to 3 files in order to check our progress. There are surely better ways than writing to multiple files. Moreover, for failures, we are writing the original requests and errors into separate files. Hard to do correlation in case there are bugs.

I propose something like this (we can figure out how to go on about this):

1. In most cases, for successful requests, we probably don't need to log them. So ignore success.log and remove that code completely. Success can just be printed on the console (perhaps via some sort of progress bar - I like that idea). 

2. Failure logs can be combined into a single file with a fixed format.

3. As mentioned above, have a progress bar to figure out our success/failure ratio. 

For successes, the user can simply use something like a "verbose" mode which prints every URL onto the console. If they want that in a file, they can simple use bash redirection. Frankly, they can do that for failures also.

Let me know your thoughts on this.

**Comment by kanishkdudeja** [comment]
> In most cases, for successful requests, we probably don't need to log them. So ignore success.log and remove that code completely. Success can just be printed on the console (perhaps via some sort of progress bar - I like that idea).

Yes, this sounds like a good idea. But, we might have to give a configurable flag to print out diagnostic information. Meaning that if a user wants a list of all the requests that were replayed or all the URLs that were hit, we should be able to provide that.

> Failure logs can be combined into a single file with a fixed format.

Yes, the important thing with this seems to be that we should make this parseable so that the user can parse this easily. JSON might be a good fit for this.

> As mentioned above, have a progress bar to figure out our success/failure ratio.

Agree here as well. If the progress bar feels too much work for the first version, we can just have the program print out the count for success, failure (request didn't get replayed), validation_failure and total logs at the end (like it's doing currently).

> For successes, the user can simply use something like a "verbose" mode which prints every URL onto the console. If they want that in a file, they can simple use bash redirection. Frankly, they can do that for failures also.

I think we should specifically develop a verbose mode which can be used for debugging. If that mode is enabled via a configured flag, we should print out in a file (probably in JSON) all of the stuff that happened like:

* Log line read
* Log line matches or does not matches configured log format
* Log line matches include-regex-pattern (something similar for exclude-regex-pattern)
* Request Attempted
* Request succeeded / failed (with status code and response time of request)

**Comment by mgill25** [comment]
Yep, verbose is a nice idea. I disagree with the idea of using JSON however. JSON-based logging is generally very helpful if the tool in question is trying to be machine-readable. But I think for now, we should be targeting humans instead of machines. So a line-based format should be used.

Something like:
`LINE_NUMBER:FORMAT_MATCH:REGEX_MATCH:REQUEST:RESPONSE_STATUS`

We can just try to do both but I think we should start with the above.

Let me know if you disagree. :)

**Comment by mgill25** [comment]
Regarding the progress bar: It's also something I consider vital from a human usability perspective. Often times, between making things extremely technical, what is left out is the user (in this case the programmer)'s experience. We often use these tools with the expectation that they will do their job "some time later" with no realistic knowledge of when that would be.

**Comment by kanishkdudeja** [comment]
> Regarding the progress bar: It's also something I consider vital from a human usability perspective. Often times, between making things extremely technical, what is left out is the user (in this case the programmer)'s experience. We often use these tools with the expectation that they will do their job "some time later" with no realistic knowledge of when that would be.

Can't agree more mate. I think we should totally do the progress bar thing unless it takes a lot of time to accomplish.

**Comment by kanishkdudeja** [comment]
> Yep, verbose is a nice idea. I disagree with the idea of using JSON however. JSON-based logging is generally very helpful if the tool in question is trying to be machine-readable. But I think for now, we should be targeting humans instead of machines. So a line-based format should be used.
> 
> Something like:
> LINE_NUMBER:FORMAT_MATCH:REGEX_MATCH:REQUEST:RESPONSE_STATUS
> 
> We can just try to do both but I think we should start with the above.
> 
> Let me know if you disagree. :)

I agree but a user might need to do something with requests that couldn't get replayed. That's why I feel that the log file should be machine readable so that a user can hack up a little script to post-process whatever we couldn't process.

A CSV file might do for now but a JSON feels more readable, both to humans and machines, in my opinion. What do you think?

**Comment by mgill25** [comment]
I guess we can always use a third party logger that supports multiple formats. I know there's plenty of those out there at least in the node.js world, so there must be some in golang as well. it's just that I'm imagining the first time user experience, they start the program and suddenly see lots of json output.

As for json being readable, yes it is - as long as it's of reasonable size. If it gets big (kinda like our log files!), then parsing them becomes a hassle and the programmer has to write more code just to do json parsing. With a line-based log format, they can predictably use grep/sed/awk.

Think of it like this - why is nginx log format not json by default?
